// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM66c4EXXKKXaP_SbsL2oTmzAUxwOX7Fc',
    appId: '1:273965387967:web:fbcecbe0dd9af77d29b60a',
    messagingSenderId: '273965387967',
    projectId: 'mindmender-1dc9a',
    authDomain: 'mindmender-1dc9a.firebaseapp.com',
    databaseURL: 'https://mindmender-1dc9a-default-rtdb.firebaseio.com',
    storageBucket: 'mindmender-1dc9a.appspot.com',
    measurementId: 'G-EWZEC4LCW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzQa6xTbZckY14B_V5usE3ww7Kzie1R2U',
    appId: '1:273965387967:android:89c2e2f5bf063d1f29b60a',
    messagingSenderId: '273965387967',
    projectId: 'mindmender-1dc9a',
    databaseURL: 'https://mindmender-1dc9a-default-rtdb.firebaseio.com',
    storageBucket: 'mindmender-1dc9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvZubS4JVvM-rjHn0_Hk0I280mwRPhBPg',
    appId: '1:273965387967:ios:be2a8a42edd401fa29b60a',
    messagingSenderId: '273965387967',
    projectId: 'mindmender-1dc9a',
    databaseURL: 'https://mindmender-1dc9a-default-rtdb.firebaseio.com',
    storageBucket: 'mindmender-1dc9a.appspot.com',
    androidClientId: '273965387967-kh0ea6mnmuhr1k52mkbl50niq745qd26.apps.googleusercontent.com',
    iosClientId: '273965387967-4a6h0juvn3jg78k8lngvatpk4iqpc7ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvZubS4JVvM-rjHn0_Hk0I280mwRPhBPg',
    appId: '1:273965387967:ios:9a0f824960494ce729b60a',
    messagingSenderId: '273965387967',
    projectId: 'mindmender-1dc9a',
    databaseURL: 'https://mindmender-1dc9a-default-rtdb.firebaseio.com',
    storageBucket: 'mindmender-1dc9a.appspot.com',
    androidClientId: '273965387967-kh0ea6mnmuhr1k52mkbl50niq745qd26.apps.googleusercontent.com',
    iosClientId: '273965387967-11drrhq9juvce6ud97eafbmt4bifvuso.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject.RunnerTests',
  );
}
